### ISSUE TITLE
Installation results in trait collision

### ISSUE THREAD

**Issue by pawelskaba** [RomainPct/Candide_PHP_FlatFiles_CMS#1]
Hi

congrats on awesome project, looks great! Unfortunately I was unable to launch it with no issues. After proper installation (according to the docs) I'm getting error:

> Fatal error: Trait method readJsonFile has not been applied, because there are collisions with other trait methods on CandideBasic in...

With a reference to: **admin/php/general/class/CandideBasic.class.php on line 18**

Thanks for any tips how to solve that :)

**Comment by RomainPct** [comment]
Hi,

This problem appears with the last version of PHP because it has became more restrif than before. I will fix it as soon as possible.

To try Candide now, you can use it on a server with PHP 7.4.2 for exemple.

Thank's a lot for your enthusiasm,
The problem will be solved soon !

**Comment by RomainPct** [comment]
Version 1.0.1 must fix these problems, can you check with the PHP version you use please ?

**Comment by pawelskaba** [comment]
I was using 7.2.19 - and it generates the error
the newest one (7.4.6) works like a charm - thx!
